imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
  environment:
    php: 7.2.13
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            tests:
                override:
                    -
                        command: "make phpunit"
                        coverage:
                            file: "build/coverage.clover"
                            format: "php-clover"